export const uiText = {
  app: {
    name: "VersusBoard",
    description: "Plataforma de juegos de mesa multijugador en tiempo real.",
    descriptionSmall: "Plataforma de juegos de mesa",
    loading: "Cargando VersusBoard...",
  },
  actions: {
    connect: "Conectarse",
    playOffline: "Jugar sin red",
    backToStart: "Volver al inicio",
    createRoom: "Crear sala",
    joinRoom: "Unirse a sala",
    creatingRoom: "Creando...",
    connectingRoom: "Conectando...",
    goToLobby: "Volver al lobby",
    instructions: "Instrucciones",
    surrender: "Rendirse",
    cancel: "Cancelar",
    close: "Cerrar",
    leaveRoom: "Salir",
    pickDark: "Yo juego con Negras",
    pickLight: "Yo juego con Blancas",
    pickMouse: "Yo soy el Raton",
    pickCat: "Yo soy el Gato",
    pickDarkLocal: "Jugador 1 con Negras",
    pickLightLocal: "Jugador 1 con Blancas",
    pickMouseLocal: "Jugador 1 sera el Raton",
    pickCatLocal: "Jugador 1 sera el Gato",
  },
  confirmations: {
    yes: "Si",
    no: "No",
    surrender: {
      title: "Rendirse",
      description: "Perderas la partida actual y volveras al lobby.",
    },
    surrenderLocal: {
      title: "Rendirse",
      description: "El jugador del turno actual pierde la partida y gana el otro jugador.",
    },
    goToLobby: {
      title: "Volver al lobby",
      description: "Salir de la partida actual te llevara de vuelta a la sala.",
    },
    goToLobbyLocal: {
      title: "Volver al selector local",
      description: "La partida actual se cerrara y volveras a elegir un juego en este telefono.",
    },
  },
  welcome: {
    title: "VersusBoard",
    subtitle: "Plataforma de juegos de mesa multijugador.",
    lobbyTitle: "Lobby principal",
    lobbySubtitle: "Crea una sala o unete a una existente",
    connectCta: "Conectarse",
  },
  forms: {
    playerNameLabel: "Tu nombre",
    playerNamePlaceholder: "Ej: Jugador1",
    roomNameLabel: "Nombre de la sala",
    roomNamePlaceholder: "Ej: Mesa de amigos",
    joinRoomLabel: "Nombre exacto de la sala",
    joinRoomPlaceholder: "Introduce el nombre de la sala",
  },
  connection: {
    waitingGuest: (room: string) =>
      `Esperando a que alguien se una a la sala "${room}"...`,
    ready: "Conectados y listos para jugar",
    unstable: "Conexion inestable: seguimos intentando reconectar...",
    offline: "Parece que no hay conexion a internet. Revisa la senal e intentalo de nuevo.",
  },
  players: {
    host: "Anfitrion",
    guest: "Invitado",
    generic: "Jugador",
    you: "(Tu)",
    waiting: "Esperando...",
    localPlayer1: "Jugador 1",
    localPlayer2: "Jugador 2",
  },
  room: {
    title: "Sala",
    createDescription: "Ambos jugadores pueden elegir el juego",
    waitingGuest: "Esperando al segundo jugador",
    reconnecting: "Buscando conexion estable...",
    localSessionName: "Partida local",
    localTitle: "Modo sin red",
    localDescription: "Elige un juego y compartan turnos en el mismo telefono.",
    cards: {
      checkers: "Juego clasico para dos.",
      comeCome: "Modo rapido inspirado en damas.",
      catMouse: "Duelo asimetrico entre felinos y raton.",
    },
  },
  games: {
    checkers: { name: "Damas" },
    comeCome: { name: "Come-Come" },
    catAndMouse: { name: "Gato y Raton" },
    generic: { name: "Juego" },
    selectToStart: "Selecciona un juego para comenzar",
    chooseRole: "Elige tu rol",
    chooseColor: "Elige tu color",
    localTurn: (playerName: string) => `Turno de ${playerName}`,
    chooseRoleDescription:
      "Tu eliges ser el Raton o el Gato; el otro jugador tendra el rol contrario.",
    chooseColorDescription:
      "Elige Blancas o Negras; tu oponente jugara con el color opuesto.",
    chooseRoleDescriptionLocal:
      "Define el rol de Jugador 1; Jugador 2 tendra el rol contrario.",
    chooseColorDescriptionLocal:
      "Define el color de Jugador 1; Jugador 2 jugara con el color opuesto.",
  },
  instructions: {
    checkers: [
      "Haz clic en una pieza para seleccionarla.",
      "Los cuadros azules indican movimientos validos.",
      "Los cuadros verdes indican capturas disponibles.",
      "Las capturas son obligatorias cuando existen.",
      "Si capturas, puedes seguir capturando en el mismo turno.",
      "Llega al otro lado del tablero para coronar tu pieza.",
    ],
    comeCome: [
      "Las piezas normales solo avanzan y capturan hacia adelante.",
      "Las piezas normales no pueden retroceder.",
      "Las damas se mueven en diagonal varias casillas.",
      "Las capturas son obligatorias cuando existen.",
      "Puedes encadenar capturas multiples en el mismo turno.",
      "Corona tu pieza al llegar al extremo opuesto.",
    ],
    catAndMouse: [
      "El raton (gris) juega primero.",
      "El raton puede moverse en diagonal en cualquier direccion.",
      "Los gatos (naranjas) solo pueden avanzar en diagonal hacia abajo.",
      "No hay capturas en este juego.",
      "El raton gana si alcanza la fila superior.",
      "Los gatos ganan si bloquean al raton sin movimientos disponibles.",
    ],
  },
  winners: {
    title: (name: string) => `Ganador: ${name}`,
    subtitle: "Vuelve al lobby para elegir otro juego o sala.",
    localSubtitle: "Vuelve al selector local para elegir otro juego.",
  },
  errors: {
    createRoom: "Error al crear la sala.",
    joinRoom: "Error al unirse a la sala.",
    missingFields: "Por favor completa tu nombre y el de la sala.",
  },
}

export type UiText = typeof uiText
